### ISSUE TITLE
Enable planner data visualization for plugin mode

### ISSUE THREAD

**Issue by henningkayser** [ros-planning/stomp_moveit#7]
Currently, only the example executable is able to publish trajectory markers to RViz. That works by running an iteration callback that converts the STOMP waypoints to trajectories which are then published using MoveItVisualTools. We could do the same inside the plugin, however we usually don't want to depend on MVT in plugins since we would introduce a circular dependency if we were to migrate stomp_moveit into the moveit2 repo. Also, it does seem hacky to use ROS publishers inside plugins just for visualization.

I think the best solution would be to add an introspection feature to the API that allows querying or subscribing to runtime planner data which supports candidate paths and stand-alone waypoints (graphs), so that the caller can decide what backend is to be used for visualization or general processing.

In addition, we should probably move a revised implementation of MVT into the moveit2 repo so that we can access it for visualizing more of MoveIt's internal state.

**Comment by simonschmeisser** [comment]
Sounds like a good GSOC project to me!
